### ISSUE TITLE
Looking for KeyDetector.h

### ISSUE THREAD

**Issue by PDE-Paul** [Spirik/GEM#103]
Hi,
I am trying your AdafruitGFX Example-01_Basic and the code will not compile as there is a missing header file #include <KeyDetector.h>, please let me know where I can find it.
Kind Regards
Paul

**Comment by Spirik** [comment]
Hello, @PDE-Paul!

Yes, @shezik is correct, examples for Adafruit GFX version of GEM rely on [KeyDetector](https://github.com/Spirik/KeyDetector) library to detect user input.

If this is your first time trying GEM, I'd suggest following step-by-step tutorial in Readme first, see [How to use with Adafruit GFX](https://github.com/Spirik/GEM?tab=readme-ov-file#how-to-use-with-adafruit-gfx) section.

**Comment by PDE-Paul** [comment]
Thank you both, my code now compiles, got another issue, will start a separate thread if needed, busy checking past issues first.
