### ISSUE TITLE
Add the 32bits float support

### ISSUE THREAD

**Issue by pailpoe** [Spirik/GEM#19]
Hello,

I use your library for a project, thanks a lot. I need to modifiy 32bits float number. I you can add this format in the library. Thanks a lot.

**Comment by pailpoe** [comment]
Thanks a lot for your fast response. I try to use char with atof(). I work on a STM32F1 board with no problem for the size of the code. 
Best regards

**Comment by Spirik** [comment]
Just for future reference: support for floating-point variables (`float` and `double`) added since version 1.2.0, see [new section](https://github.com/Spirik/GEM#floating-point-variables) in Readme for implementation specifics.
