### ISSUE TITLE
Setting conditional pages

### ISSUE THREAD

**Issue by HajmamadAgha** [Spirik/GEM#62]
I'm going to put some variables on the same pages and I want them to be limited, e.g. when setting variable X and pushing the next button it shouldn't be able to get lower than 2 and if so I want to show an error and go back to the page.

**Comment by Spirik** [comment]
Sorry, not quite sure that I understand correctly, but it seems to me that what you want is to implement some sort of validation callback. It is possible, please see my reply to your other posted [issue](https://github.com/Spirik/GEM/issues/63). If this is not the case, please clarify what are you trying to achieve.
