### ISSUE TITLE
Limiting float and integer variable

### ISSUE THREAD

**Issue by HajmamadAgha** [Spirik/GEM#63]
When choosing a variable item I want it to be limited so the user won't be able to increase it more than a maximum or decrease it less than the minimum, how should I implement it?
I used the constrain function but it doesn't work.

**Comment by Spirik** [comment]
Hi, **HajmamadAgha**!

The proper way to achieve this currently is through callback function, which will be called when menu item is saved. You can write validation routine there, comparing saved value to desired min and max thresholds and act accordingly (e.g. overwriting value that user just saved).

For more details. please, see corresponding section in [wiki](https://github.com/Spirik/GEM/wiki/How-to#add-menu-item-callback-basic) and [Blink](https://github.com/Spirik/GEM/wiki/Example-02%3A-Blink) and [Party Hard!](https://github.com/Spirik/GEM/wiki/Example-03%3A-Party-Hard%21) examples (which features validation callbacks for `interval` variables).
